[phases.setup]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan filament:upgrade",
    "php artisan migrate --force"
]

[phases.build]
aptPkgs = ["...", "php8.2-gd", "php8.2-zip", "php8.2-bcmath", "php8.2-xml", "php8.2-curl", "php8.2-mbstring"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
